const plan2023Obligatorias = [
    {
        nombreMateria: "CBC",
        correlativas: [],
        equivalencias: ["CBC"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 38,
    },
    {
        nombreMateria: "Análisis Matemático 2",
        correlativas: ["CBC"],
        equivalencias: ["Análisis Matemático 2"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 8,
    },
    {
        nombreMateria: "Física de los Sistemas de Partículas",
        correlativas: ["CBC"],
        equivalencias: ["Física 1"],
        creditoExcedentePorEquivalencia: 2,
        creditos: 6,
    },
    {
        nombreMateria: "Introducción a la Ingeniería Electrónica",
        correlativas: ["CBC"],
        equivalencias: ["Introducción a la Ingeniería Electrónica"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Algoritmos y Programación",
        correlativas: ["CBC"],
        equivalencias: ["Algoritmos y Programación 1"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Álgebra Lineal",
        correlativas: ["CBC"],
        equivalencias: ["Álgebra 2"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 8,
    },
    {
        nombreMateria: "Electricidad, Magnetismo y Calor",
        correlativas: ["Análisis Matemático 2", "Física de los Sistemas de Partículas"],
        equivalencias: ["Física 2"],
        creditoExcedentePorEquivalencia: 2,
        creditos: 6,
    },
    {
        nombreMateria: "Introducción a los Dispositivos Electrónicos",
        correlativas: ["Introducción a la Ingeniería Electrónica"],
        equivalencias: ["Dispositivos Semiconductores"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 4,
    },
    {
        nombreMateria: "Sistemas Digitales",
        correlativas: ["Introducción a la Ingeniería Electrónica"],
        equivalencias: ["Técnica Digital"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Probabilidad y Estadística",
        correlativas: ["Análisis Matemático 2", "Álgebra Lineal"],
        equivalencias: ["Probabilidad y Estadística"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Señales y Sistemas",
        correlativas: ["Análisis Matemático 2", "Álgebra Lineal"],
        equivalencias: ["Señales y Sistemas"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Análisis de Circuitos",
        correlativas: ["Introducción a la Ingeniería Electrónica", "Electricidad, Magnetismo y Calor"],
        equivalencias: ["Análisis de Circuitos"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Redes de Comunicaciones",
        correlativas: ["CBC"],
        equivalencias: ["Comunicación de Datos"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Planificación de Proyectos",
        correlativas: ["Introducción a la Ingeniería Electrónica"],
        equivalencias: ["Introducción a Proyectos"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 2,
    },
    {
        nombreMateria: "Circuitos Microelectrónicos",
        correlativas: ["Introducción a los Dispositivos Electrónicos", "Análisis de Circuitos"],
        equivalencias: ["Circuitos Electrónicos"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Procesos Estocásticos",
        correlativas: ["Probabilidad y Estadística", "Señales y Sistemas"],
        equivalencias: ["Procesos Estocásticos"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Control Automático",
        correlativas: ["Electricidad, Magnetismo y Calor", "Señales y Sistemas"],
        equivalencias: ["Control Automático 1"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Taller de Sistemas Embebidos",
        correlativas: ["Algoritmos y Programación", "Introducción a los Dispositivos Electrónicos", "Sistemas Digitales"],
        equivalencias: ["Laboratorio de Microprocesadores"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Química y Electroquímica",
        correlativas: ["Electricidad, Magnetismo y Calor"],
        equivalencias: ["Química"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Electromagnetismo Aplicado",
        correlativas: ["Análisis de Circuitos"],
        equivalencias: ["Electromagnetismo"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 4,
    },
    {
        nombreMateria: "Taller de Automatización y Control",
        correlativas: ["Algoritmos y Programación", "Control Automático", "Sistemas Digitales"],
        equivalencias: ["Laboratorio de Control Automático", "Control Industrial Distribuido"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Taller de Procesamiento de Señales",
        correlativas: ["Procesos Estocásticos"],
        equivalencias: ["Teoría de Detección y Estimación", "Procesamiento de Imágenes", "Procesamiento de Señales I"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Dispositivos Semiconductores",
        correlativas: ["Introducción a los Dispositivos Electrónicos", "Análisis de Circuitos"],
        equivalencias: ["Física 3"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Taller de Comunicaciones Digitales",
        correlativas: ["Señales y Sistemas", "Redes de Comunicaciones"],
        equivalencias: ["Comunicaciones Digitales I"],
        creditos: 6,
    },
    {
        nombreMateria: "Taller de Diseño de Circuitos Electrónicos",
        correlativas: ["Circuitos Microelectrónicos", "Electromagnetismo Aplicado"],
        equivalencias: ["Diseño de Circuitos Electrónicos"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Higiene y Seguridad",
        correlativas: [],
        creditosRequeridos: 100,
        equivalencias: ["Seguridad Ambiental y del Trabajo"],
        creditoExcedentePorEquivalencia: 2,
        creditos: 2,
    },
    {
        nombreMateria: "Legislación y Ejercicio Profesional",
        correlativas: [],
        creditosRequeridos: 100,
        equivalencias: ["Legislación y Ejercicio Profesional de la Ingeniería Electrónica"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 2,
    },
    {
        nombreMateria: "Gestión de Proyectos Electrónicos",
        correlativas: ["Planificación de Proyectos"],
        equivalencias: ["Introducción a la Economía y Organización de la Empresa"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Impacto Social, Ambiental y Desarrollo Sustentable",
        correlativas: [],
        creditosRequeridos: 100,
        equivalencias: [],
        creditoExcedentePorEquivalencia: 0,
        creditos: 4,
    },
    {
        nombreMateria: "Trabajo Integrador Final de Ingeniería Electrónica",
        correlativas: ["Planificación de Proyectos", "Taller de Sistemas Embebidos", "Taller de Automatización y Control", "Taller de Procesamiento de Señales", "Taller de Diseño de Circuitos Electrónicos"],
        equivalencias: ["Tesis - Trabajo Profesional"],
        creditoExcedentePorEquivalencia: 6,
        creditos: 12,
    },
]

export { plan2023Obligatorias }
// module.exports = { plan2023Obligatorias }