const plan2023Obligatorias = [
    {
        nombreMateria: "CBC",
        correlativas: [],
        equivalencias: ["CBC"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 38,
    },
    {
        nombreMateria: "Analisis Matematico 2",
        correlativas: ["CBC"],
        equivalencias: ["Analisis Matematico 2"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 8,
    },
    {
        nombreMateria: "Fisica de los Sistemas de Particulas",
        correlativas: ["CBC"],
        equivalencias: ["Fisica 1"],
        creditoExcedentePorEquivalencia: 2,
        creditos: 6,
    },
    {
        nombreMateria: "Introduccion a la Ingenieria Electronica",
        correlativas: ["CBC"],
        equivalencias: ["Introduccion a la Ingenieria Electronica"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Algoritmos y Programacion",
        correlativas: ["CBC"],
        equivalencias: ["Algoritmos y Programacion 1"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Algebra Lineal",
        correlativas: ["CBC"],
        equivalencias: ["Algebra 2"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 8,
    },
    {
        nombreMateria: "Electricidad, Magnetismo y Calor",
        correlativas: ["Analisis Matematico 2", "Fisica de los Sistemas de Particulas"],
        equivalencias: ["Fisica 2"],
        creditoExcedentePorEquivalencia: 2,
        creditos: 6,
    },
    {
        nombreMateria: "Introduccion a los Dispositivos Electronicos",
        correlativas: ["Introduccion a la Ingenieria Electronica"],
        equivalencias: ["Dispositivos Semiconductores"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 4,
    },
    {
        nombreMateria: "Sistemas Digitales",
        correlativas: ["Introduccion a la Ingenieria Electronica"],
        equivalencias: ["Tecnica Digital"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Probabilidad y Estadistica",
        correlativas: ["Analisis Matematico 2", "Algebra Lineal"],
        equivalencias: ["Probabilidad y Estadistica"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Señales y Sistemas",
        correlativas: ["Analisis Matematico 2", "Algebra Lineal"],
        equivalencias: ["Señales y Sistemas"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Analisis de Circuitos",
        correlativas: ["Introduccion a la Ingenieria Electronica", "Electricidad, Magnetismo y Calor"],
        equivalencias: ["Analisis de Circuitos"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Redes de Comunicaciones",
        correlativas: ["CBC"],
        equivalencias: ["Comunicacion de Datos"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Planificacion de Proyectos",
        correlativas: ["Introduccion a la Ingenieria Electronica"],
        equivalencias: ["Introduccion a Proyectos"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 2,
    },
    {
        nombreMateria: "Circuitos Microelectronicos",
        correlativas: ["Introduccion a los Dispositivos Electronicos", "Analisis de Circuitos"],
        equivalencias: ["Circuitos Electronicos"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Procesos Estocasticos",
        correlativas: ["Probabilidad y Estadistica", "Señales y Sistemas"],
        equivalencias: ["Procesos Estocasticos"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Control Automatico",
        correlativas: ["Electricidad, Magnetismo y Calor", "Señales y Sistemas"],
        equivalencias: ["Control Automatico 1"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Taller de Sistemas Embebidos",
        correlativas: ["Algoritmos y Programacion", "Introduccion a los Dispositivos Electronicos", "Sistemas Digitales"],
        equivalencias: ["Laboratorio de Microprocesadores"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Quimica y Electroquimica",
        correlativas: ["Electricidad, Magnetismo y Calor"],
        equivalencias: ["Quimica"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Electromagnetismo Aplicado",
        correlativas: ["Analisis de Circuitos"],
        equivalencias: ["Electromagnetismo"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 4,
    },
    {
        nombreMateria: "Taller de Automatizacion y Control",
        correlativas: ["Algoritmos y Programacion", "Control Automatico", "Sistemas Digitales"],
        equivalencias: ["Laboratorio de Control Automático", "Control Industrial Distribuido"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Taller de Procesamiento de Señales",
        correlativas: ["Procesos Estocasticos"],
        equivalencias: ["Teoría de Detección y Estimación", "Procesamiento de Imágenes", "Procesamiento de Señales I"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Dispositivos Semiconductores",
        correlativas: ["Introduccion a los Dispositivos Electronicos", "Analisis de Circuitos"],
        equivalencias: ["Fisica 3"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Taller de Comunicaciones Digitales",
        correlativas: ["Señales y Sistemas", "Redes de Comunicaciones"],
        equivalencias: ["Comunicaciones Digitales I"],
        creditos: 6,
    },
    {
        nombreMateria: "Taller de Diseño de Circuitos Electronicos",
        correlativas: ["Circuitos Microelectronicos", "Electromagnetismo Aplicado"],
        equivalencias: ["Diseño de Circuitos Electronicos"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Higiene y Seguridad",
        correlativas: [],
        creditosRequeridos: 100,
        equivalencias: ["Seguridad Ambiental y del Trabajo"],
        creditoExcedentePorEquivalencia: 2,
        creditos: 2,
    },
    {
        nombreMateria: "Legislacion y Ejercicio Profesional",
        correlativas: [],
        creditosRequeridos: 100,
        equivalencias: ["Legislacion y Ejercicio Profesional de la Ingenieria Electronica"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 2,
    },
    {
        nombreMateria: "Gestion de Proyectos Electronicos",
        correlativas: ["Planificacion de Proyectos"],
        equivalencias: ["Introduccion a la Economia y Organizacion de la Empresa"],
        creditoExcedentePorEquivalencia: 0,
        creditos: 6,
    },
    {
        nombreMateria: "Legislacion y Ejercicio Profesional",
        correlativas: [],
        creditosRequeridos: 100,
        equivalencias: [],
        creditoExcedentePorEquivalencia: 0,
        creditos: 4,
    },
    {
        nombreMateria: "Trabajo Integrador Final de Ingenieria Electronica",
        correlativas: ["Planificacion de Proyectos", "Taller de Sistemas Embebidos", "Taller de Automatizacion y Control", "Taller de Procesamiento de Señales", "Taller de Diseño de Circuitos Electronicos"],
        equivalencias: ["Tesis - Trabajo Profesional"],
        creditoExcedentePorEquivalencia: 6,
        creditos: 12,
    },
]

export { plan2023Obligatorias }
