const plan2023Electivas = [
    {
        nombreMateria: "Comunicaciones Inalámbricas",
        correlativas: ["Electromagnetismo Aplicado", "Taller de Comunicaciones Digitales"],
        equivalencias: ["Sistemas Inalámbricos"],
        creditos: 4,
    },
    {
        nombreMateria: "Instrumentos Electrónicos y Metrologia",
        correlativas: ["Taller de Diseño de Circuitos Electrónicos"],
        equivalencias: ["Instrumentos y Mediciones Electrónicas"],
        creditos: 4,
    },
    {
        nombreMateria: "Electrónica de Alta Frecuencia",
        correlativas: ["Taller de Diseño de Circuitos Electrónicos"],
        equivalencias: ["Transmisores y Receptores de Comunicaciones"],
        creditos: 4,
    },
    {
        nombreMateria: "Internet de las Cosas",
        correlativas: ["Taller de Comunicaciones Digitales"],
        equivalencias: [],
        creditos: 4,
    },
    {
        nombreMateria: "Infraestructura de Redes",
        correlativas: ["Taller de Comunicaciones Digitales"],
        equivalencias: ["Infraestructura de Redes Fijas", "Servicios y Redes de Comunicaciones"],
        creditos: 4,
    },
    {
        nombreMateria: "Propagación y Sistemas Irradiantes",
        correlativas: ["Electromagnetismo Aplicado"],
        equivalencias: ["Propagación y Sistemas Irradiantes"],
        creditos: 4,
    },
    {
        nombreMateria: "Compatibilidad Electromagnética",
        correlativas: ["Taller de Diseño de Circuitos Electrónicos"],
        equivalencias: ["Compatibilidad Electromagnética"],
        creditos: 4,
    },
    {
        nombreMateria: "Laboratorio de Comunicaciones",
        correlativas: ["Taller de Comunicaciones Digitales"],
        equivalencias: ["Laboratorio de Comunicaciones"],
        creditos: 4,
    },
    {
        nombreMateria: "Redes Neuronales y Aprendizaje Profundo",
        correlativas: ["Taller de Procesamiento de Señales"],
        equivalencias: ["Redes Neuronales"],
        creditos: 4,
    },
    {
        nombreMateria: "Aprendizaje por Refuerzo",
        correlativas: ["Taller de Procesamiento de Señales"],
        equivalencias: [],
        creditos: 6,
    },
    {
        nombreMateria: "Vision por computadora",
        correlativas: ["Taller de Procesamiento de Señales"],
        equivalencias: [],
        creditos: 4,
    },
    {
        nombreMateria: "Procesamiento del Habla",
        correlativas: ["Taller de Procesamiento de Señales"],
        equivalencias: ["Procesamiento del Habla"],
        creditos: 4,
    },
    {
        nombreMateria: "Optimización Convexa",
        correlativas: ["Procesos Estocásticos"],
        equivalencias: [],
        creditos: 6,
    },
    {
        nombreMateria: "Procesamiento Estadístico de Señales",
        correlativas: ["Procesos Estocásticos"],
        equivalencias: ["Procesamiento de Señales II"],
        creditos: 4,
    },
    {
        nombreMateria: "Taller de Sistemas Digitales",
        correlativas: ["Sistemas Digitales", "Señales y Sistemas"],
        equivalencias: ["Sistemas Digitales"],
        creditos: 6,
    },
    {
        nombreMateria: "Diseño y Verificación Digital",
        correlativas: ["Taller de Sistemas Embebidos"],
        equivalencias: ["Laboratorio de Sistemas Digitales"],
        creditos: 6,
    },
    {
        nombreMateria: "Sistemas Operativos",
        correlativas: ["Taller de Sistemas Embebidos"],
        equivalencias: ["Sistemas Operativos"],
        creditos: 6,
    },
    {
        nombreMateria: "Algoritmos y Estructuras de Datos",
        correlativas: ["Algoritmos y Programación"],
        equivalencias: ["Algoritmos y Programación II"],
        creditos: 6,
    },
    {
        nombreMateria: "Sistemas Operativos Embebidos",
        correlativas: ["Taller de Sistemas Embebidos"],
        equivalencias: [],
        creditos: 4,
    },
    {
        nombreMateria: "Instrumentación y Control de Procesos Industriales",
        correlativas: ["Taller de Automatización y Control"],
        equivalencias: ["Instrumentación y Control de Procesos"],
        creditos: 4,
    },
    {
        nombreMateria: "Control Automático Avanzado",
        correlativas: ["Taller de Automatización y Control"],
        equivalencias: ["Control Automático III"],
        creditos: 4,
    },
    {
        nombreMateria: "Control Automático Multivariable",
        correlativas: ["Taller de Automatización y Control"],
        equivalencias: ["Control Automático II"],
        creditos: 4,
    },
    {
        nombreMateria: "Identificación y Control Adaptativo",
        correlativas: ["Taller de Automatización y Control"],
        equivalencias: ["Identificación y Control Adaptativo"],
        creditos: 4,
    },
    {
        nombreMateria: "Electrónica de Potencia",
        correlativas: ["Circuitos Microelectrónicos"],
        equivalencias: ["Electrónica de Potencia"],
        creditos: 4,
    },
    {
        nombreMateria: "Accionamientos Variables",
        correlativas: ["Circuitos Microelectrónicos", "Control Automático"],
        equivalencias: ["Accionamientos Variables"],
        creditos: 6,
    },
    {
        nombreMateria: "Robótica Movil",
        correlativas: ["Procesos Estocásticos", "Algoritmos y Programación"],
        equivalencias: [],
        creditos: 4,
    },
    {
        nombreMateria: "Robotica Industrial",
        correlativas: ["Taller de Automatización y Control"],
        equivalencias: ["Robótica"],
        creditos: 6,
    },
    {
        nombreMateria: "Microelectrónica",
        correlativas: ["Circuitos Microelectrónicos", "Dispositivos Semiconductores"],
        equivalencias: ["Microelectrónica"],
        creditos: 4,
    },
    {
        nombreMateria: "Laboratorio de Microelectrónica",
        correlativas: ["Microelectrónica"],
        equivalencias: ["Laboratorio de Microelectrónica"],
        creditos: 4,
    },
    {
        nombreMateria: "Comunicación y Computación Cuántica",
        correlativas: ["Taller de Sistemas Embebidos"],
        equivalencias: [],
        creditos: 4,
    },
    {
        nombreMateria: "Dispositivos Optoelectrónicos Avanzados",
        correlativas: ["Dispositivos Semiconductores"],
        equivalencias: [],
        creditos: 4,
    },
    {
        nombreMateria: "Optoelectrónica",
        correlativas: ["Dispositivos Semiconductores"],
        equivalencias: ["Optoelectrónica"],
        creditos: 4,
    },
    {
        nombreMateria: "Introducción a la Ingeniería Acústica",
        correlativas: ["Señales y Sistemas"],
        equivalencias: ["Acústica"],
        creditos: 4,
    },
    {
        nombreMateria: "Acústica de Recintos",
        correlativas: ["Señales y Sistemas"],
        equivalencias: [],
        creditos: 4,
    },
    {
        nombreMateria: "Electroacústica",
        correlativas: ["Circuitos Microelectrónicos"],
        equivalencias: ["Electroacústica"],
        creditos: 4,
    },
    {
        nombreMateria: "Audio Profesional",
        correlativas: ["Taller de Diseño de Circuitos Electrónicos"],
        equivalencias: ["Audio Profesional"],
        creditos: 4,
    },
    {
        nombreMateria: "Ciberseguridad de Redes e Infraestructuras",
        correlativas: ["Algoritmos y Programación", "Taller de Comunicaciones Digitales"],
        equivalencias: ["Criptografía y Seguridad Informática"],
        creditos: 6,
    },
    {
        nombreMateria: "Sistemas Gráficos",
        correlativas: ["Algoritmos y Programación"],
        equivalencias: ["Sistemas Gráficos"],
        creditos: 4,
    },
    {
        nombreMateria: "Introducción a la Industria, los Sistemas y el Negocio Aeroespacial",
        correlativas: [],
        creditosRequeridos: 120,
        equivalencias: [],
        creditos: 6,
    },
    {
        nombreMateria: "Tecnología de Materiales para la industria Aeroespacial B",
        correlativas: ["Electricidad, Magnetismo y Calor", "Química y Electroquímica"],
        equivalencias: [],
        creditos: 4,
    },
    {
        nombreMateria: "Comunicaciones Aeroespaciales B",
        correlativas: ["Taller de Comunicaciones Digitales"],
        equivalencias: [],
        creditos: 2,
    },
]

export { plan2023Electivas }
// module.exports = { plan2023Electivas }